 services:
  - type: web
    name: flask-xelatex
    runtime: python
    buildCommand: |
      apt-get update \
      && apt-get install -y texlive-xetex \
      && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
